### ISSUE TITLE
Apologies for having to do this

### ISSUE THREAD

**Issue by jabberwockxeno** [gglover/pokepalettes.com#1]
I realize that this certainly isn't the right place to let you know about this, but I wanted to let you know that the email you have listed on your site (gglover@uw.edu) isn't working. 

I tried to send you a suggestion regarding this project there, but my email provider says the messages are undeliverable. 

Again, sorry I had to create an issue here to let you know, I but your github seemed like the only other place I could reach you at. If there's another method of contact that I could send the actual suggestion at, let me know.

**Comment by gglover** [comment]
Ouch that's frustrating, I had a few others come through earlier today. I've been meaning to switch off the rat's nest of public university IT. 

You can reach me at gus.glov3r@gmail.com for now.
I'll close this once I get a dedicated mail server up on my domain. Thanks for letting me know!
