### ISSUE TITLE
Make Color Codes Copy Paste-able

### ISSUE THREAD

**Issue by torch2424** [gglover/pokepalettes.com#2]
Hello!

Just wanted to say I LOVE pokemon palletes, and I use it to design all of my personal sites/apps,

My only issue with it is that whenever you try to copy the color codes, they often cause an action or are a link, and I was hoping They were copy pasteable.

I dont mind forking the repo and doing it myself, just wanted to hear your thoughts on the idea. Thanks! :)

**Comment by gglover** [comment]
Apologies for lack of response from a 6 year old me; gotta make good before 2021 at least!
Should keep the text highlight now.
cheers :)

**Comment by torch2424** [comment]
No worries at all! :smile: I maintain a few older projects of mine from time to time so I totally understand haha! 

Thanks for the fix! :+1:
