### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by hycner** [gglover/pokepalettes.com#3]
First of all, thank you for creating this lovely project in the first place. It has always been my go-to for getting color palettes for personal projects.

I was heartbroken today when I tried to visit the site and found that it was down.

I found this repo and tried to run things but it seems like the current setup in the repo either isn't sufficient to run the project. I'm sure you've probably moved on to other things but I was wondering if it was possible to assist in making the full setup available so that it can be run?

I'd also be happy to help take things over and get a .com up again so that this gem is available for people to use again.

Either way thanks for creating this in the first place!

**Comment by gglover** [comment]
Hey James,

I've still got the domain, I just moved a bunch of stuff off of Digital Ocean a couple months back and forgot to rehost pokepalettes. Thanks for letting me know! Really glad people are still using this :) I'm going to migrate to github pages and bring everything back online. Also making all of the assets available so you can do a local build.

Cheers!

**Comment by hycner** [comment]
Such a great surprise in the new year! Thanks for everything!
